update get-ip

diff --git a/.github/workflows/infra-and-deploy.yml b/.github/workflows/infra-and-deploy.yml
--- a/.github/workflows/infra-and-deploy.yml
+++ b/.github/workflows/infra-and-deploy.yml
@@ -43,7 +43,11 @@ jobs:
       - name: Get EC2 Public IP
         id: get_ip
         run: |
-          IP=$(terraform output -raw ec2_public_ip 2>/dev/null | tr -d '\r')
+          IP=$(terraform output -raw ec2_public_ip 2>/dev/null || echo "")
+          if [ -z "$IP" ]; then
+            echo "EC2 public IP not found. Exiting..."
+            exit 1
+          fi
           echo "EC2_HOST=$IP" >> $GITHUB_ENV
 
   deploy:
